version: '3.8'

services:
  app:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: eugene
      POSTGRES_PASSWORD: Eugene007@
      POSTGRES_DB: newslett
    volumes:
      - ./config:/app/config
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: eugene
      POSTGRES_PASSWORD: Eugene007@
      POSTGRES_DB: newslett
    ports:
      - "5432:5432"
    
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com 
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"  # Access pgAdmin at http://localhost:8080
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge